
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
wallets:
  from_keys: ${PRIVATE_KEY}

networks:
  rinkeby:
    eth_usd_pricefeed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    publish_source: True
  mainnet-fork-dev:
    eth_usd_pricefeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    publish_source: False
  kovan:
    eth_usd_pricefeed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    publish_source: True
  mainnet:
    eth_usd_pricefeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    publish_source: True
  ganache-local:
    public_source: False